name: getx_template
description: "Production-ready generic Flutter starter template with GetX and Clean Architecture."
repository: https://github.com/parentroots/getx
issue_tracker: https://github.com/parentroots/getx/issues
version: 1.0.1

environment:
  sdk: ">=3.9.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cached_network_image: ^4.0.0
  connectivity_plus: ^7.3.1
  cupertino_icons: ^1.0.9
  dio: ^5.11.0
  file_picker: ^12.1.2
  firebase_core: ^4.14.0
  firebase_messaging: ^16.6.0
  flutter_secure_storage: ^11.0.0
  flutter_svg: ^2.3.0
  flutter_screenutil: ^5.9.3
  get: ^4.7.3
  image_picker: ^1.2.3
  intl: ^0.20.2
  intl_phone_field: ^3.2.0
  country_picker: ^2.0.28
  logger: ^2.7.0
  pretty_dio_logger: ^1.4.0
  permission_handler: ^13.0.1
  shared_preferences: ^2.5.5
  socket_io_client: ^3.1.6
  shimmer: ^4.0.0
  url_launcher: ^6.3.2
  pinput: ^6.0.2

  

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    - assets/animations/
